# Generated by Django 2.0.13 on 2019-08-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ablum_logo',
            new_name='album_logo',
        ),
    ]
